const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const $=s=>document.querySelector(s),intro=$('#intro'),pause=$('#pause'),over=$('#gameOver');
const keys=new Set();let game,last=0,raf;const highKey='echo-dark-high-score';$('#highScore').textContent=localStorage.getItem(highKey)||0;
function createMaze(cols,rows){const cells=Array.from({length:rows},()=>Array.from({length:cols},()=>({walls:[1,1,1,1],seen:false}))),stack=[[0,0]],dirs=[[0,-1,0,2],[1,0,1,3],[0,1,2,0],[-1,0,3,1]];cells[0][0].seen=true;while(stack.length){let[x,y]=stack.at(-1),o=dirs.filter(([dx,dy])=>cells[y+dy]?.[x+dx]&&!cells[y+dy][x+dx].seen);if(!o.length){stack.pop();continue}let[dx,dy,a,b]=o[Math.random()*o.length|0],n=cells[y+dy][x+dx];cells[y][x].walls[a]=0;n.walls[b]=0;n.seen=true;stack.push([x+dx,y+dy])}return cells}
function start(){cancelAnimationFrame(raf);game={cols:33,rows:23,maze:null,player:{x:0,y:0,angle:0},diamonds:[],battery:100,elapsed:0,score:0,collected:0,expandAt:30,moveCooldown:0,running:true,paused:false,dead:false,flicker:0};buildWorld();intro.classList.add('hidden');over.classList.add('hidden');pause.classList.add('hidden');last=performance.now();raf=requestAnimationFrame(loop)}
function buildWorld(keep=false){let p=game.player;game.maze=createMaze(game.cols,game.rows);game.player=keep?{x:Math.min(p.x,game.cols-1),y:Math.min(p.y,game.rows-1),angle:p.angle}:{x:0,y:0,angle:0};game.diamonds=[];let used=new Set([game.player.x+','+game.player.y]),add=type=>{let x,y,k;do{x=Math.random()*game.cols|0;y=Math.random()*game.rows|0;k=x+','+y}while(used.has(k));used.add(k);game.diamonds.push({x,y,type,pulse:Math.random()*6})};for(let i=0;i<Math.max(8,Math.floor(game.cols*game.rows/34));i++)add('blue');add('gold')}
function addBlue(){let g=game,p=g.player,a=[];for(let y=0;y<g.rows;y++)for(let x=0;x<g.cols;x++)if(!g.diamonds.some(d=>d.x===x&&d.y===y)&&Math.hypot(x-p.x,y-p.y)>=6)a.push({x,y});if(a.length){let s=a[Math.random()*a.length|0];g.diamonds.push({...s,type:'blue',pulse:Math.random()*6})}}
function attempt(dx,dy){let p=game.player,d=dx===1?1:dx===-1?3:dy===1?2:0;if(!game.maze[p.y][p.x].walls[d]){p.x+=dx;p.y+=dy;p.angle=Math.atan2(dy,dx);for(let i=game.diamonds.length-1;i>=0;i--){let q=game.diamonds[i];if(q.x===p.x&&q.y===p.y){game.battery=Math.min(100,game.battery+(q.type==='gold'?50:25));game.collected++;game.diamonds.splice(i,1);if(q.type==='blue')addBlue()}}}}
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Escape','r','R'].includes(e.key))e.preventDefault();if(e.key==='r'||e.key==='R')start();if(e.key==='Escape'&&game&&!game.dead){game.paused=!game.paused;pause.classList.toggle('hidden',!game.paused);last=performance.now()}if(e.key.startsWith('Arrow'))keys.add(e.key)});addEventListener('keyup',e=>keys.delete(e.key));$('#startButton').onclick=start;$('#restartButton').onclick=start;
function loop(now){let dt=Math.min(.05,(now-last)/1000);last=now;if(!game.paused&&!game.dead)update(dt);draw();raf=requestAnimationFrame(loop)}
function update(dt){let g=game;g.elapsed+=dt;g.score=Math.floor(g.elapsed/3);g.battery=Math.max(0,g.battery-(g.elapsed>10?.05:.03)*dt*100);g.flicker=Math.max(0,g.flicker-dt);let chance=g.battery<10?.45:g.battery<25?.22:g.battery<50?.07:0;if(chance&&Math.random()<dt*chance)g.flicker=.1+Math.random()*.16;g.moveCooldown-=dt;if(g.moveCooldown<=0){let m={ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0]}[[...keys].at(-1)];if(m){attempt(...m);g.moveCooldown=.07}}if(g.battery===0)end();if(g.elapsed>=g.expandAt){g.cols+=2;g.rows+=2;g.expandAt+=30;buildWorld(true);g.battery=Math.min(100,g.battery+12)}hud()}
function end(){game.dead=true;let h=Math.max(game.score,+localStorage.getItem(highKey)||0);localStorage.setItem(highKey,h);$('#highScore').textContent=h;$('#finalScore').textContent=game.score;$('#finalDiamonds').textContent=game.collected;$('#finalHigh').textContent=h;over.classList.remove('hidden')}
function hud(){let b=game.battery;$('#score').textContent=game.score;$('#diamonds').textContent=game.collected;$('#batteryText').textContent=Math.ceil(b)+'%';let f=$('#batteryFill');f.style.width=b+'%';f.style.background=b<10?'#ff5261':b<25?'#ffad56':'#5cf6a4';$('#statusText').textContent=b===0?'LIGHT LOST':b<10?'SEVERE FLICKERING':b<25?'FREQUENT FLICKERING':b<50?'UNSTABLE LIGHT':'STABLE LIGHT'}
function draw(){let g=game||{cols:33,rows:23,maze:createMaze(33,23),player:{x:0,y:0,angle:0},diamonds:[],battery:100},w=canvas.width,h=canvas.height,c=Math.min(w/g.cols,h/g.rows),ox=(w-g.cols*c)/2,oy=(h-g.rows*c)/2,r=!g.running?999:g.battery===0?0:Math.max(1.2,1.55+g.battery/42)*(g.flicker?Math.random()*.55+.3:1);ctx.fillStyle='#07100d';ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(108,154,132,.62)';ctx.lineWidth=2;for(let y=0;y<g.rows;y++)for(let x=0;x<g.cols;x++){if(Math.hypot(x-g.player.x,y-g.player.y)>r)continue;let a=g.maze[y][x].walls,X=ox+x*c,Y=oy+y*c;ctx.globalAlpha=Math.min(1,(r-Math.hypot(x-g.player.x,y-g.player.y)+.7)/1.3);ctx.beginPath();if(a[0]){ctx.moveTo(X,Y);ctx.lineTo(X+c,Y)}if(a[1]){ctx.moveTo(X+c,Y);ctx.lineTo(X+c,Y+c)}if(a[2]){ctx.moveTo(X+c,Y+c);ctx.lineTo(X,Y+c)}if(a[3]){ctx.moveTo(X,Y+c);ctx.lineTo(X,Y)}ctx.stroke()}ctx.globalAlpha=1;for(let d of g.diamonds){if(Math.hypot(d.x-g.player.x,d.y-g.player.y)>r+.35)continue;let x=ox+(d.x+.5)*c,y=oy+(d.y+.5)*c,z=c*.18;ctx.save();ctx.shadowBlur=16;ctx.shadowColor=d.type==='gold'?'#ffd45d':'#41b6ff';ctx.fillStyle=ctx.shadowColor;ctx.translate(x,y);ctx.rotate(Math.PI/4);ctx.fillRect(-z,-z,z*2,z*2);ctx.restore()}let x=ox+(g.player.x+.5)*c,y=oy+(g.player.y+.5)*c;ctx.save();ctx.translate(x,y);ctx.rotate(g.player.angle);ctx.shadowBlur=18;ctx.shadowColor='#5cf6a4';ctx.fillStyle='#5cf6a4';ctx.beginPath();ctx.moveTo(c*.32,0);ctx.lineTo(-c*.21,-c*.2);ctx.lineTo(-c*.1,0);ctx.lineTo(-c*.21,c*.2);ctx.closePath();ctx.fill();ctx.restore()}draw();